Format: 1A
Host: 

# TODO: Change me at Fictium.configuration.api




# Information and references

API version: 0.1.0

# Group Resources 

# Open libraries [/api/open_library]
Handles api open_library.


## Show details of an open library. [GET ]

+ Response 200 (application/json)
 
  + Body

      ```
      {"ISBN":"2","title":"Pragmatic Realism, Religious Truth, and Antitheodicy","subtitle":"On Viewing the World by Acknowledging the Other","number_of_pages":223,"authors":[{"url":"https://openlibrary.org/authors/OL5422937A/Sami_Pihlström","name":"Sami Pihlström"}]}
      ```


+ Response 404 (application/json)
 
  + Body

      ```
      {"message":"Book not found"}
      ```
