default: &default
  mailer:
    user_name: <%= ENV["MAILER_USERNAME"] %>
    password: <%= ENV["MAILER_PASSWORD"] %>
    address: <%= ENV["MAILER_ADDRESS"] %>
    domain: <%= ENV["MAILER_DOMAIN"] %>
    port: <%= ENV["MAILER_PORT"] %>
    authentication: <%= ENV["MAILER_AUTHENTICATION"] %>

development:
  <<: *default

test:
  <<: *default